// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhrjbdvknhgsypfhrpbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlocmpiZHZrbmhnc3lwZmhycGJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjkxMjcsImV4cCI6MjA2NDgwNTEyN30.-e4hDj6aGxP-ltCA2elLN2csjpSM2FK9Eh0OPH89bbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);